name: "Install Rust for Substrate"
description: "Install Rust configured for Substrate"
author: "Standard Tech"
branding:
  icon: 'archive'  
  color: 'gray-dark'

inputs:
  nightly_toolchain_build:
    description: "Which version of rust toolchain to use"
    required: false
    default: "nightly-2021-04-22"

runs:
  using: "composite"
  steps:
    - name: Install Rustup
      shell: bash
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env
        rustup default stable
        rustup update stable
        rustup install ${{ inputs.nightly_toolchain_build }}
        rustup target add wasm32-unknown-unknown --toolchain ${{ inputs.nightly_toolchain_build }}
